import { PROBLEMS, PROBLEM_MAP } from "@/lib/data/problems";

// Maps a Striver-A2Z problem title to a Beacon library problem slug (when we
// have full teaching content for it), so the course can deep-link into it.

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

const TITLE_TO_SLUG = new Map<string, string>();
for (const p of PROBLEMS) TITLE_TO_SLUG.set(norm(p.title), p.slug);

// A few hand-curated aliases where the A2Z naming differs from ours.
const ALIASES: Record<string, string> = {
  "2sumproblem": "two-sum",
  kadanesalgorithm: "maximum-subarray",
  stockbuysell: "best-time-to-buy-sell-stock",
  longestconsecutivesubsequence: "longest-consecutive-sequence",
  mergeoverlappingsubinterval: "merge-intervals",
  searchxinsortedarray: "binary-search",
  lowestcommonancestorofabinarysearchtree: "lowest-common-ancestor-of-a-bst",
  // A2Z / course naming → Beacon slugs (hand-verified as the SAME problem).
  numberofsubarraysumequalk: "subarray-sum-equals-k",
  pascaltriangle: "pascals-triangle",
  findtheminimumelementinsortedrotatedarray: "find-minimum-in-rotated-sorted-array",
  findsingleelementinsortedarray: "single-element-in-a-sorted-array",
  reversewordsinstring: "reverse-words-in-a-string",
  lettercombinationsofphone: "letter-combinations-of-a-phone-number",
  kthlargestelement: "kth-largest-element-in-an-array",
  kthlargestelementinstream: "kth-largest-element-in-a-stream",
  kthsmallestelementinbst: "kth-smallest-element-in-a-bst",
  cheapestflightswithkstops: "cheapest-flights-within-k-stops",
  besttimetobuyandsellstocks: "best-time-to-buy-sell-stock",
  levelordertraversal: "binary-tree-level-order-traversal",
  maximumpathsum: "binary-tree-maximum-path-sum",
  lowestcommonancestor: "lowest-common-ancestor-of-a-bst",
  nextgreaterelement: "next-greater-element-i",
  longestrepeatingcharacter: "longest-repeating-character-replacement",
  implementminstack: "min-stack",
  wordsearchingrid: "word-search",
  mergeksortedarrays: "merge-k-sorted-lists",
  searchinrotatedsortedarraywithduplicates: "search-in-rotated-sorted-array",
  combinationsum1: "combination-sum",
  combinationsum2: "combination-sum-ii",
  jumpgame2: "jump-game-ii",
  houserobber2: "house-robber-ii",
  sort012: "sort-colors",
  setmatrix0s: "set-matrix-zeroes",
  rotatematrix: "rotate-image",
  spiraltraversal: "spiral-matrix",
  findxinsortedarray: "binary-search",
  kokoeatingbanana: "koko-eating-bananas",
  majorityelement2: "majority-element-ii",
  searchinsortedmatrix: "search-a-2d-matrix",
  searchinrowwisesortedmatrix: "search-a-2d-matrix",
  validparenthesis: "valid-parentheses",
  // A2Z course names → newly-authored batch K/L/M/N problems.
  subarrayswithxork: "subarray-with-given-xor",
  largestsubarraywith0sum: "largest-subarray-with-zero-sum",
  merge2sortedarraywithoutspace: "merge-sorted-array",
  repeatingandmissingnumbers: "set-mismatch",
  longestsubarraywithgivensum: "longest-subarray-with-sum-k",
  longestsubarraywithsumkcontaingvesandves: "longest-subarray-with-sum-k",
  rearangeelementsbysign: "rearrange-array-elements-by-sign",
  leadersinarray: "leaders-in-an-array",
  unionof2sortedarrays: "union-of-two-sorted-arrays",
  findelementpresentonlyonce: "single-number",
  squarerootofnumber: "sqrt-x",
  nthrootofinteger: "nth-root-of-a-number",
  minimumdaystomakeboquets: "minimum-number-of-days-to-make-m-bouquets",
  capacitytoshippackages: "capacity-to-ship-packages-within-d-days",
  aggresivecows: "aggressive-cows",
  bookallocation: "allocate-minimum-number-of-pages",
  splitarraylargest: "split-array-largest-sum",
  kthmissingnumber: "kth-missing-positive-number",
  firstandlastposition: "find-first-and-last-position-of-element-in-sorted-array",
  peakelementinmatrix: "find-peak-element-ii",
  isomorphicstring: "isomorphic-strings",
  implementatoi: "string-to-integer-atoi",
  removeouterparenthesis: "remove-outermost-parentheses",
  maxnestingdepthofparenthesis: "maximum-nesting-depth-of-the-parentheses",
  checkforrotatedstring: "rotate-string",
  sortll: "sort-list",
  sort012inll: "sort-linked-list-of-0s-1s-and-2s",
  oddevenll: "odd-even-linked-list",
  rotatellktimes: "rotate-list",
  deletemidofll: "delete-the-middle-node-of-a-linked-list",
  add1toll: "add-one-to-a-linked-list",
  reverseknodeingroups: "reverse-nodes-in-k-group",
  flattenall: "flatten-a-linked-list",
  // --- Trees ---
  preordertraversal: "binary-tree-preorder-traversal",
  postordertraversal: "binary-tree-postorder-traversal",
  inordertraversal: "binary-tree-inorder-traversal",
  iterativepreordertraversal: "iterative-preorder-traversal-of-binary-tree",
  iterativeinordertraversal: "iterative-inorder-traversal-of-binary-tree",
  iterativepostorder: "iterative-postorder-traversal-of-binary-tree",
  zigzagtraversal: "binary-tree-zigzag-level-order-traversal",
  boundarytraversal: "boundary-traversal-of-binary-tree",
  verticalordertraversal: "vertical-order-traversal-of-a-binary-tree",
  topview: "top-view-of-binary-tree",
  bottomview: "bottom-view-of-binary-tree",
  leftorrightview: "right-view-of-binary-tree",
  allroottoleafpaths: "root-to-leaf-paths-in-binary-tree",
  maxwidthofbinarytree: "maximum-width-of-binary-tree",
  checkchildrensumproperty: "children-sum-property-in-binary-tree",
  allnodesatdistancek: "all-nodes-distance-k-in-binary-tree",
  mintimetoburnbinarytree: "minimum-time-to-burn-a-binary-tree",
  countnodesincompletebinarytree: "count-complete-tree-nodes",
  constructbtfrominorderandpostorder: "construct-binary-tree-from-inorder-and-postorder-traversal",
  constructbtfrominorderandpreorder: "construct-binary-tree-from-preorder-and-inorder-traversal",
  flattenbinarytree: "flatten-binary-tree-to-linked-list",
  serializeanddeserialize: "serialize-and-deserialize-binary-tree",
  // --- BST ---
  searchinbst: "search-in-a-binary-search-tree",
  minimumvalueinbst: "minimum-element-in-bst",
  ceilinbst: "ceil-in-a-bst",
  floorinbst: "floor-in-a-bst",
  insertintobst: "insert-into-a-binary-search-tree",
  deletefrombst: "delete-node-in-a-bst",
  buildbstfrompreordertraversal: "construct-bst-from-preorder-traversal",
  bstiterator: "binary-search-tree-iterator",
  twosuminbst: "two-sum-iv-input-is-a-bst",
  recoverbst: "recover-binary-search-tree",
  largestbstinbinarytree: "largest-bst-in-a-binary-tree",
  validatebst: "validate-binary-search-tree",
  lcainbst: "lowest-common-ancestor-of-a-bst",
  // --- Graphs ---
  bfs: "bfs-of-graph",
  dfs: "dfs-of-graph",
  countthenumberofprovinces: "number-of-provinces",
  rottenoranges: "rotting-oranges",
  floodfillalgorithm: "flood-fill",
  detectcycleinundirectedgraph: "detect-cycle-in-an-undirected-graph",
  detectcycleindirectedgraph: "detect-cycle-in-a-directed-graph",
  bipartitegraph: "is-graph-bipartite",
  topologicalsorting: "topological-sort",
  kahnsalgorithm: "topological-sort",
  coursescheduler1: "course-schedule",
  coursescheduler2: "course-schedule-ii",
  findeventualsafestate: "find-eventual-safe-states",
  aliendictonary: "alien-dictionary",
  numberofenclaves: "number-of-enclaves",
  distinctislands: "number-of-distinct-islands",
  shortestpathinundirectedgraphhavingunitdistance: "shortest-path-in-undirected-graph-with-unit-weights",
  shortestpathindag: "shortest-path-in-a-dag",
  primsalgorithm: "prims-algorithm-minimum-spanning-tree",
  kruskalsalgorithm: "kruskals-algorithm-minimum-spanning-tree",
  numberofoperationstomakenetwork: "number-of-operations-to-make-network-connected",
  moststonesremoved: "most-stones-removed-with-same-row-or-column",
  accountmerge: "accounts-merge",
  numberofislands2: "number-of-islands-ii",
  makinglargeisland: "making-a-large-island",
  findcitywithsmallestnumberofneighbours:
    "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance",
  // --- DP ---
  findthenthfibonaccinumber: "nth-fibonacci-number",
  frogkjumps: "frog-jump-with-k-distances",
  ninjatraining: "ninjas-training",
  minimumpathsum: "minimum-path-sum-in-grid",
  minimumpathintriangle: "triangle-minimum-path-sum",
  subsetsumequaltok: "subset-sum-equal-to-target",
  partitionarrayintwoequalsumsubsets: "partition-equal-subset-sum",
  minimumsumpartition: "minimum-subset-sum-difference",
  countnumberofsubsetswithsumk: "count-subsets-with-sum-k",
  partitionwithgivendifference: "count-partitions-with-given-difference",
  "01knapsack": "0-1-knapsack",
  rodcuttingproblem: "rod-cutting",
  printthelcs: "longest-common-subsequence",
  minimumstepstomakestringpalindrome: "minimum-insertions-to-make-string-palindrome",
  besttimetobuyandsellstock2: "best-time-to-buy-and-sell-stock-ii",
  besttimetobuyandsellstockupto2transaction: "best-time-to-buy-and-sell-stock-iii",
  besttimetobuyandsellstockuotoktransaction: "best-time-to-buy-and-sell-stock-iv",
  buyandsellstockswithcooldown: "best-time-to-buy-and-sell-stock-with-cooldown",
  buyandsellstockswithtransactionfee: "best-time-to-buy-and-sell-stock-with-transaction-fee",
  printlis: "longest-increasing-subsequence",
  numberoflis: "number-of-longest-increasing-subsequence",
  mcm: "matrix-chain-multiplication",
  minimumcosttocutstick: "minimum-cost-to-cut-a-stick",
  burstballons: "burst-balloons",
  palindormepartionting2: "palindrome-partitioning-ii",
  countsquaresubmatrices: "count-square-submatrices-with-all-ones",
  // --- Heaps / Greedy / Tries / hard strings ---
  minimumcosttojoinnropes: "connect-n-ropes-with-minimum-cost",
  maximumksumcombinations: "maximum-sum-combinations",
  medianinastream: "find-median-from-data-stream",
  lemonadeexchange: "lemonade-change",
  maximumxoroftwonumbers: "maximum-xor-of-two-numbers-in-an-array",
  minimumnumberofinsertionstomakeparenthesisvalid: "minimum-add-to-make-parentheses-valid",
  countsubsetswithsumequaltok: "count-subsets-with-sum-k",
  // --- Recursion / Backtracking ---
  genereateallvalidparenthesis: "generate-parentheses",
  powerset: "power-set",
  combinationsum3: "combination-sum-iii",
  ratinmaze: "rat-in-a-maze",
  mcoloringproblem: "m-coloring-problem",
  sudokusolver: "sudoku-solver",
  implementatoiviarecursion: "implement-atoi-using-recursion",
  countgoodnumbers: "count-good-numbers",
  reversestackusingrecursion: "reverse-a-stack-using-recursion",
  sortstackusingrecursion: "sort-a-stack-using-recursion",
  subset1: "subsets",
  subset2: "subsets-ii",
  palindormepartioning: "palindrome-partitioning",
  palindromepartioning: "palindrome-partitioning",
  alinoneTraversal: "binary-tree-preorder-traversal",
  allinonetraversal: "binary-tree-preorder-traversal",
  countdistinctsubstrings: "count-distinct-substrings-using-trie",
  countdistinctsubsitrings: "count-distinct-substrings-using-trie",
  // --- Bit / Math ---
  checkfortheithbit: "check-if-the-kth-bit-is-set",
  checkforoddeven: "check-if-a-number-is-odd-or-even-using-bits",
  checkforthepowerof2: "check-if-a-number-is-a-power-of-two",
  settherighmostunsetbit: "set-the-rightmost-unset-bit",
  swaptwonumberswithouttemporaryvariable: "swap-two-numbers-without-temp",
  dividetwonumbersusingbitmaipulation: "divide-two-integers-without-multiplication",
  countsetbitfromnumbers1ton: "count-set-bits-from-1-to-n",
  minimumbitflips: "minimum-bit-flips-to-convert-number",
  exceptionallyodd: "number-appearing-odd-number-of-times",
  xorofnumbersfromltor: "xor-of-numbers-from-l-to-r",
  primefactorsofnumber: "prime-factors-of-a-number",
  alldivisorsofnumber: "all-divisors-of-a-number",
  primefactorizationusingsieve: "smallest-prime-factor-using-sieve",
  fastpower: "fast-exponentiation",
  // --- Stack / Queue ---
  infixtopostfix: "infix-to-postfix-conversion",
  infixtoprefix: "infix-to-prefix-conversion",
  prefixtoinfix: "prefix-to-infix-conversion",
  postfixtoinfix: "postfix-to-infix-conversion",
  nextgreaterelement2: "next-greater-element-ii",
  previoussmallerelement: "previous-smaller-element",
  sumofsubarrayminimum: "sum-of-subarray-minimums",
  sumofrangeofallsubarray: "sum-of-subarray-ranges",
  removekelements: "remove-k-digits",
  maximalrectangleinbinarymatrix: "maximal-rectangle",
  asteroidscollision: "asteroid-collision",
  stockspanproblem: "stock-span-problem",
  celebrityproblem: "the-celebrity-problem",
  // --- Sliding Window ---
  maxconsecutive1s: "maximum-consecutive-ones",
  fruitintobaskets: "fruit-into-baskets",
  binarysubarrayswithsum: "binary-subarrays-with-sum",
  countthenumberofnicesubarrays: "count-number-of-nice-subarrays",
  numberofsubstringscontainingall3characters:
    "number-of-substrings-containing-all-three-characters",
  maximumpointsyoucanobtalnformthecard: "maximum-points-you-can-obtain-from-cards",
  longestsubstringwithatmostkuniquecharacters:
    "longest-substring-with-at-most-k-distinct-characters",
  countthenumberofsubstringswithexactlykuniquecharacters:
    "count-substrings-with-k-distinct-characters",
  countthenumberofsubstringswithkuniquecharacters: "count-substrings-with-k-distinct-characters",
  sumofbeautyofallsubstrings: "sum-of-beauty-of-all-substrings",
  // --- Arrays / Binary Search basics ---
  rotatearrayleftby1place: "rotate-array-by-k-places",
  "rotatearrayleftrightbykplaces": "rotate-array-by-k-places",
  move0stoend: "move-zeroes-to-end",
  implementlowerbound: "lower-bound",
  implementlowerupperbound: "upper-bound",
  numberofoccurences: "count-occurrences-in-sorted-array",
  findhowmanytimesarrayisrotated: "number-of-times-sorted-array-is-rotated",
  rowwithmaximumnumberof1s: "row-with-maximum-ones",
  matrixmedian: "median-of-row-wise-sorted-matrix",
  findsmallestinteger: "find-the-smallest-missing-positive-number",
  // --- Linked List / DLL ---
  insertingnodetolinkedlist: "insert-a-node-in-singly-linked-list",
  deletingnodeinlinkedlist: "delete-a-node-in-singly-linked-list",
  countthenumberofnodeslinkedlist: "length-of-a-linked-list",
  searchelementinlinkedlist: "search-an-element-in-linked-list",
  insertnodeindll: "insert-a-node-in-doubly-linked-list",
  deletenodeindll: "delete-a-node-in-doubly-linked-list",
  reversedll: "reverse-a-doubly-linked-list",
  findmidofll: "middle-of-the-linked-list",
  reversell: "reverse-linked-list",
  detectloopinll: "linked-list-cycle",
  startofcycleinll: "linked-list-cycle-ii",
  countnodesinloop: "length-of-loop-in-linked-list",
  checkforpalindromell: "palindrome-linked-list",
  deletenthnodefromback: "remove-nth-node-from-end-of-list",
  addtwoll: "add-two-numbers",
  deletenodesfromdll: "delete-a-node-in-doubly-linked-list",
  pairsumindll: "pairs-with-given-sum-in-doubly-linked-list",
  removeduplicatesfromdll: "remove-duplicates-from-sorted-doubly-linked-list",
  copyllwithrandompointers: "copy-list-with-random-pointer",
  flattenll: "flatten-a-linked-list",
  // --- Graphs / Heap leftovers ---
  numberofwaystoarrivethedestinationwithminimumdistance:
    "number-of-ways-to-arrive-at-destination",
  checkifarrayisheap: "check-if-array-represents-a-min-heap",
  convertminheaptomaxheap: "convert-min-heap-to-max-heap",
  kthsmallestelement: "kth-smallest-element-in-an-array",
  arrangebyrank: "replace-each-element-with-rank-in-array",
  dividearrayintosetsofkconsecutivenumber: "divide-array-into-sets-of-k-consecutive-numbers",
  // --- Tries / DP / String leftovers ---
  uniquepaths2: "unique-paths-ii",
  minimumstepstomakeotherstring: "minimum-insertions-and-deletions-to-convert-string",
  partitionarrayformaximumsum: "partition-array-for-maximum-sum",
  completestring: "longest-word-with-all-prefixes",
  implementtrie2: "implement-trie-ii",
};

export function librarySlugForTitle(title: string): string | undefined {
  const n = norm(title);
  const direct = TITLE_TO_SLUG.get(n);
  if (direct) return direct;
  const alias = ALIASES[n];
  // Guard: only return an alias that actually resolves to a real problem.
  return alias && PROBLEM_MAP[alias] ? alias : undefined;
}
